//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeadPipe.Net.Validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeadPipe.Net.Validation.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field cannot contain leading whitespace..
        /// </summary>
        internal static string CanNotContainLeadingWhitespace {
            get {
                return ResourceManager.GetString("CanNotContainLeadingWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field cannot contain lower case letters..
        /// </summary>
        internal static string CanNotContainLowerCaseLetters {
            get {
                return ResourceManager.GetString("CanNotContainLowerCaseLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field cannot contain trailing whitespace..
        /// </summary>
        internal static string CanNotContainTrailingWhitespace {
            get {
                return ResourceManager.GetString("CanNotContainTrailingWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field cannot contain upper case case letters..
        /// </summary>
        internal static string CanNotContainUpperCaseLetters {
            get {
                return ResourceManager.GetString("CanNotContainUpperCaseLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field cannot contain whitespace characters..
        /// </summary>
        internal static string CanNotContainWhitespace {
            get {
                return ResourceManager.GetString("CanNotContainWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field can only contain letters..
        /// </summary>
        internal static string CanOnlyContainLetters {
            get {
                return ResourceManager.GetString("CanOnlyContainLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field can only contain letters and numbers..
        /// </summary>
        internal static string CanOnlyContainLettersAndNumbers {
            get {
                return ResourceManager.GetString("CanOnlyContainLettersAndNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field can only contain letters and these characters ({1})..
        /// </summary>
        internal static string CanOnlyContainLettersAndSpecialCharacters {
            get {
                return ResourceManager.GetString("CanOnlyContainLettersAndSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field can only contain letters, numbers and these characters ({1})..
        /// </summary>
        internal static string CanOnlyContainLettersNumbersAndSpecialCharacters {
            get {
                return ResourceManager.GetString("CanOnlyContainLettersNumbersAndSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field can only contain numbers..
        /// </summary>
        internal static string CanOnlyContainNumbers {
            get {
                return ResourceManager.GetString("CanOnlyContainNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field can only contain numbers and these characters ({1})..
        /// </summary>
        internal static string CanOnlyContainNumbersAndSpecialCharacters {
            get {
                return ResourceManager.GetString("CanOnlyContainNumbersAndSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field can only contain characters from the the printable character list ({1})..
        /// </summary>
        internal static string CanOnlyContainPrintableCharacters {
            get {
                return ResourceManager.GetString("CanOnlyContainPrintableCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field can only contain these characters ({1})..
        /// </summary>
        internal static string CanOnlyContainSpecialCharacters {
            get {
                return ResourceManager.GetString("CanOnlyContainSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field must not exceed {1} characters long..
        /// </summary>
        internal static string ValueGreaterThanMaximumLength {
            get {
                return ResourceManager.GetString("ValueGreaterThanMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field must be at least {1} characters long..
        /// </summary>
        internal static string ValueLessThanMinimumLength {
            get {
                return ResourceManager.GetString("ValueLessThanMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field must be greater than or equal to {1}..
        /// </summary>
        internal static string ValueMustBeGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("ValueMustBeGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field must be less than or equal to {1}..
        /// </summary>
        internal static string ValueMustBeLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("ValueMustBeLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field must be numeric..
        /// </summary>
        internal static string ValueMustBeNumeric {
            get {
                return ResourceManager.GetString("ValueMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field must be a string..
        /// </summary>
        internal static string ValueMustBeString {
            get {
                return ResourceManager.GetString("ValueMustBeString", resourceCulture);
            }
        }
    }
}
